server:
  port: 9095
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spachigolla05/spring-cloud-config-repo.git
          timeout: 500
          searchPaths: >
            proj-employee-survey

